config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/moment/moment:
      branch: develop
      repo: https://github.com/moment/moment
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/moment/moment git:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-copper-beaver.sh
        container: qc.acc_jumpy-denim-tarantula
  QC.Doc:
    repos:
      github.com/moment/moment find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-lemon-dragonfly.sh
        container: qc.doc_craggy-burgundy-olm
      github.com/moment/moment git:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-crimson-mongoose.sh
        container: qc.doc_silly-russet-avocet
      github.com/moment/moment markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-sepia-koala.sh
        container: qc.doc_crappy-tangerine-ant
  QC.FAIR:
    repos:
      github.com/moment/moment F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-purple-quail.sh
        container: qc.fair_flaky-sangria-tetra
  QC.Lic:
    repos:
      github.com/moment/moment licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-wisteria-fossa.sh
        container: qc.lic_woolly-maroon-foxhound
  QC.Ver:
    repos:
      github.com/moment/moment get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-alizarin-chihuahua.sh
        container: qc.ver_skinny-amethyst-capybara
timeout: 1800
